### PR TITLE
downgrade react-dev-utils so 'yarn start' works

### LINKED ISSUE #834: "webpack is not a function" when 'yarn start'
Ever since the upgrade from [react-dev-utils 7.0.5 to 8.0.0](https://github.com/mozilla/delivery-console/pull/823/files) `yarn start` stopped working: https://irccloud.mozilla.com/pastebin/b8q2yd77/

I have verified, on `master` that this works:

```bash
▶ yarn add react-dev-utils@7.0.5
▶ yarn start
```

### PR DESCRIPTION
**Pull request by peterbe**
Fixes #834

### CODE REVIEW

**Comment by peterbe** [comment]
bors retry
